edgetpu: fix -Wcast-function-type-strict
Building this driver with the newer AOSP Clang 17.0.0 produces the
following error:

  private/google-modules/edgetpu/abrolhos/drivers/edgetpu/edgetpu-device-group.c:1007:4:
  error: cast from 'int (*)(struct iova_mapping_worker_param *)' to
  'edgetpu_async_job_t' (aka 'int (*)(void *)') converts to incompatible
  function type [-Werror,-Wcast-function-type-strict]
  (edgetpu_async_job_t)edgetpu_map_iova_sgt_worker);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Fix this by declaring edgetpu_map_iova_sgt_worker have the correct
signature, cast the parameter in edgetpu_map_iova_sgt_worker, and remove
the function pointer cast.  This warning was added to clang to help
catch CFI failures at compile time rather than runtime.

Bug: 264965700
Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>
Change-Id: I969c812db523e02a3d873fb9a93ddf84702d1925
(cherry picked from commit b61a36d7cb4ba2413b732694d16b4dde74bf77c6)